### ISSUE TITLE
Performance benchmark of EOS EVM Miner versions

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/eos-evm-miner#30]
Compare performance of current EOS EVM Miner vs https://github.com/pinax-network/eos-evm-miner

**Comment by stephenpdeos** [comment]
We also want to compare different versions of leap nodes such as v4.0.5 and v5.0.0-rc3

**Comment by stephenpdeos** [comment]
We want to run this on the Jungle4 EOS EVM Contract

**Comment by stephenpdeos** [comment]
Also validate that wharfkit is used here

**Comment by yarkinwho** [comment]
**Testing methods:**

Launch N process, each sending 20 simple transactions (send 0 eos to some account) one by one with an interval of one second. Count the time required to finish all requests to calculate the TPS.

**Initial Results:**
|           | 100    | 200     | 400     | 800     |
| --------- | ------ | ------- | ------- | ------- |
| new miner | 61.965 | 62.115  | 61.928  | 61.622  |
| 1 miner   | 82.903 | 106.207 | 97.836  | 85.83   |
| 2 miner   | 89.236 | 167.728 | 208.77  | 188.89  |
| 4 miner   | 92.066 | 179.621 | 279.742 | 315.917 |

![image](https://github.com/eosnetworkfoundation/eos-evm-miner/assets/99302011/e5cdfe86-b65c-4a74-90c3-430bb46496f8)

The figure show the resulting TPS when we use different number of process sending requests.

**Observation:**
It's clear that the new miner have worse performance comparing to the old one. Possibly because it's more complicated and has more functionalities. But this need separate investigation. 

From the data for the old miner, we can see that one miner can serve at most ~100 TPS with that machine. CPU consumption for the miners shows miners are all at 100% with high concurrency.
To find if this is the case for more miners we switched to an 8 core machine.

** More Results:**
|         | TPS      | Fail rate |
| ------- | -------- | --------- |
| 1 miner | 84.631   | 11.25%    |
| 2 miner | 198.7883 | 6.83%     |
| 4 miner | 396.8893 | 0.56%     |
| 8 miner | 382.0843 | 2.20%     |

We collected this data on a new machine with 8 cores. And recored the fail rate.
for 4 and 8 miner settings, fails are all "Wrong nonce", which means the leap have not process the tx in time.
for 1 and 2 miners, majority of the error is time out, which means the miners are overwhelmed.

**Discussion:**
The result for 8 miner setting is interesting. It shows the leap can only serve somewhere between 4-8 miners at most. more miner will effectively block the leap and cause the performance to drop.

Therefore, we can conclude from the current result that keeping our current miner with 4 miner to one leap setting is fine for now.

**Future Works:**

1. The current test method is still not fully simulate the real work case. So the TPS number may not reflect the real world TPS perfectly. We Should try to improve the testing framework. e.g. let each process wait after each requests but add more processes to get a more realistic TPS.
2. Try to figure out the bottleneck of leap
3. Figure out why the new miner is slow. Test whether if it will perform better with more realistic test settings.

Use https://github.com/eosnetworkfoundation/eos-evm-internal/issues/146 to track future works.
